[package]
name = "memon"
version = "0.1.0"
edition = "2024"
authors = ["Your Name <you@example.com>"]
description = "A memory monitor tool that analyzes memory usage of processes and their children"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
